import jsPDF from "jspdf";

interface ShotListItem {
  shot_type: string;
  visual: string;
  rationale: string;
  image_prompt?: string;
}

interface Scene {
  id: string;
  scene_number: number;
  header: string;
  content: string;
  analysis: string | null;
  status: string;
}

interface AnalysisData {
  story_analysis: {
    stakes: string;
    ownership: string;
    breaking_point: string;
    key_props: string;
  };
  producing_logistics: {
    red_flags: string[];
    resource_impact: "Low" | "Medium" | "High";
    departments_affected: string[];
  };
  directing_vision: {
    visual_metaphor: string;
    editorial_intent: string;
    shot_motivation: string;
  };
}

const parseAnalysis = (analysisString: string | null): AnalysisData | null => {
  if (!analysisString) return null;
  
  try {
    return JSON.parse(analysisString);
  } catch {
    return null;
  }
};

const isShotListItem = (shot: string | ShotListItem): shot is ShotListItem => {
  return typeof shot === 'object' && shot !== null && 'shot_type' in shot;
};

export const exportShotListPDF = async (scenes: Scene[], projectTitle: string) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = 25;

  // White background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Header
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(0, 0, 0);
  pdf.text("SHOT LIST", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 100);
  pdf.text(projectTitle, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 12;

  // Divider
  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  let shotNumber = 1;

  scenes.forEach((scene) => {
    const analysis = parseAnalysis(scene.analysis);
    
    // Skip scenes without analysis or in the new format
    if (!analysis) return;

    // Scene Header
    if (yPosition > pageHeight - 40) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 25;
    }

    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text(`SCENE ${scene.scene_number}: ${scene.header.replace(/\n/g, ' ')}`, margin, yPosition);
    yPosition += 8;

    // Display story analysis
    if (analysis.story_analysis?.stakes) {
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(229, 9, 20);
      pdf.text("STAKES:", margin + 5, yPosition);
      yPosition += 4;
      
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(60, 60, 60);
      const stakesLines = pdf.splitTextToSize(analysis.story_analysis.stakes, maxWidth - 10);
      pdf.text(stakesLines, margin + 10, yPosition);
      yPosition += stakesLines.length * 4 + 4;
    }

    yPosition += 8;
  });

  // Footer
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} • Generated by ShotLogic`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  pdf.save(`${projectTitle}-shot-list.pdf`);
};

export const exportShotListCSV = (scenes: Scene[], projectTitle: string) => {
  const rows: string[][] = [
    ['Scene', 'Stakes', 'Breaking Point', 'Resource Impact']
  ];

  scenes.forEach((scene) => {
    const analysis = parseAnalysis(scene.analysis);
    
    if (!analysis) return;

    rows.push([
      `Scene ${scene.scene_number}`,
      analysis.story_analysis?.stakes || 'N/A',
      analysis.story_analysis?.breaking_point || 'N/A',
      analysis.producing_logistics?.resource_impact || 'N/A'
    ]);
  });

  // Convert to CSV string
  const csvContent = rows.map(row => 
    row.map(cell => `"${cell}"`).join(',')
  ).join('\n');

  // Download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${projectTitle}-shot-list.csv`;
  link.click();
};
