import jsPDF from "jspdf";

interface ShotListItem {
  shot_number?: number;
  shot_type: string;
  movement?: string;
  subject?: string;
  action?: string;
  visual?: string;
  visualDescription?: string;
  rationale: string;
  editorial_intent?: string;
  duration?: string;
  image_prompt?: string;
  aiImagePrompt?: string;
  coverage?: string;
}

interface Scene {
  id: string;
  scene_number: number;
  header: string;
  content: string;
  analysis: string | null;
  status: string;
}

interface AnalysisData {
  story_analysis: {
    stakes: string;
    ownership: string;
    breaking_point: string;
    key_props: string;
    synopsis?: string;
    subtext?: string;
    tone?: string;
  };
  producing_logistics: {
    red_flags: string[];
    resource_impact: "Low" | "Medium" | "High";
    departments_affected: string[];
    key_props?: string[];
    wardrobe?: string[];
    special_requirements?: string[];
    locations?: {
      primary?: string;
      setting?: string;
      timeOfDay?: string;
      intExt?: string;
    };
    cast?: {
      principal?: string[];
      speaking?: string[];
      silent?: string[];
      extras?: { count?: string; description?: string };
    };
  };
  directing_vision: {
    visual_metaphor?: string;
    editorial_intent?: string;
    shot_motivation?: string;
    visual_approach?: string;
    performance_notes?: string[] | string;
    subtext?: string;
    conflict?: {
      type?: string;
      description?: string;
      winner?: string;
    };
    tone_and_mood?: {
      opening?: string;
      shift?: string;
      closing?: string;
      energy?: string;
    };
    visual_strategy?: {
      approach?: string;
      camera_personality?: string;
      lighting_mood?: string;
    };
    character_motivations?: Array<{
      character?: string;
      wants?: string;
      obstacle?: string;
      tactic?: string;
    }>;
    key_moments?: Array<{
      beat?: string;
      emphasis?: string;
      why?: string;
    }>;
    blocking?: {
      geography?: string;
      movement?: string;
      eyelines?: string;
    };
  };
  shot_list?: ShotListItem[];
}

const parseAnalysis = (analysisString: string | null): AnalysisData | null => {
  if (!analysisString) return null;
  try {
    return JSON.parse(analysisString);
  } catch {
    return null;
  }
};

export const exportShotListPDF = async (scenes: Scene[], projectTitle: string) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = 20;

  const checkPageBreak = (neededSpace: number) => {
    if (yPosition + neededSpace > pageHeight - 20) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 20;
      return true;
    }
    return false;
  };

  // White background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title Page Header
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(229, 9, 20); // Netflix red
  pdf.text("FULL ANALYSIS REPORT", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(0, 0, 0);
  pdf.text(projectTitle, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;

  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${scenes.length} Scenes • Generated by ShotLogic`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  scenes.forEach((scene, sceneIndex) => {
    const analysis = parseAnalysis(scene.analysis);
    if (!analysis) return;

    // Start each scene on new page (except first)
    if (sceneIndex > 0) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 20;
    }

    // ═══════════════════════════════════════════════════════════════
    // SCENE HEADER
    // ═══════════════════════════════════════════════════════════════
    pdf.setFillColor(40, 40, 40);
    pdf.rect(margin, yPosition - 5, maxWidth, 12, 'F');
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.setTextColor(255, 255, 255);
    pdf.text(`SCENE ${scene.scene_number}`, margin + 3, yPosition + 3);
    yPosition += 12;

    // Scene slug line
    pdf.setFillColor(60, 60, 60);
    pdf.rect(margin, yPosition - 3, maxWidth, 8, 'F');
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(255, 255, 255);
    const headerText = scene.header.substring(0, 100) + (scene.header.length > 100 ? '...' : '');
    pdf.text(headerText, margin + 3, yPosition + 2);
    yPosition += 12;

    // ═══════════════════════════════════════════════════════════════
    // STORY ANALYSIS SECTION
    // ═══════════════════════════════════════════════════════════════
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(229, 9, 20);
    pdf.text("STORY ANALYSIS", margin, yPosition);
    yPosition += 6;

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(8);

    // Synopsis
    if (analysis.story_analysis?.synopsis) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Synopsis:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const synopsisLines = pdf.splitTextToSize(analysis.story_analysis.synopsis, maxWidth - 5);
      yPosition += 4;
      pdf.text(synopsisLines, margin + 2, yPosition);
      yPosition += synopsisLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Conflict/Ownership
    if (analysis.story_analysis?.ownership) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Conflict:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const ownershipLines = pdf.splitTextToSize(analysis.story_analysis.ownership, maxWidth - 5);
      yPosition += 4;
      pdf.text(ownershipLines, margin + 2, yPosition);
      yPosition += ownershipLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Scene Turn
    if (analysis.story_analysis?.breaking_point) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Scene Turn:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const turnLines = pdf.splitTextToSize(analysis.story_analysis.breaking_point, maxWidth - 5);
      yPosition += 4;
      pdf.text(turnLines, margin + 2, yPosition);
      yPosition += turnLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Stakes
    if (analysis.story_analysis?.stakes) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Stakes:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const stakesLines = pdf.splitTextToSize(analysis.story_analysis.stakes, maxWidth - 5);
      yPosition += 4;
      pdf.text(stakesLines, margin + 2, yPosition);
      yPosition += stakesLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Tone
    if (analysis.story_analysis?.tone || analysis.directing_vision?.visual_metaphor) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Tone:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const toneText = analysis.story_analysis?.tone || analysis.directing_vision?.visual_metaphor || '';
      const toneLines = pdf.splitTextToSize(toneText, maxWidth - 5);
      yPosition += 4;
      pdf.text(toneLines, margin + 2, yPosition);
      yPosition += toneLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    yPosition += 4;

    // ═══════════════════════════════════════════════════════════════
    // DIRECTING VISION SECTION
    // ═══════════════════════════════════════════════════════════════
    const dv = analysis.directing_vision;
    if (dv) {
      checkPageBreak(40);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(229, 9, 20);
      pdf.text("DIRECTING VISION", margin, yPosition);
      yPosition += 6;
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(8);

      // Tone & Mood
      if (dv.tone_and_mood) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Tone & Mood:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        if (dv.tone_and_mood.opening) {
          pdf.text(`Opens: ${dv.tone_and_mood.opening}`, margin + 2, yPosition);
          yPosition += 4;
        }
        if (dv.tone_and_mood.shift) {
          const shiftLines = pdf.splitTextToSize(`Shifts: ${dv.tone_and_mood.shift}`, maxWidth - 5);
          pdf.text(shiftLines, margin + 2, yPosition);
          yPosition += shiftLines.length * 3.5;
        }
        if (dv.tone_and_mood.closing) {
          pdf.text(`Closes: ${dv.tone_and_mood.closing}`, margin + 2, yPosition);
          yPosition += 4;
        }
        if (dv.tone_and_mood.energy) {
          pdf.text(`Energy: ${dv.tone_and_mood.energy}`, margin + 2, yPosition);
          yPosition += 4;
        }
        yPosition += 2;
        checkPageBreak(20);
      }

      // Visual Strategy
      if (dv.visual_strategy) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Visual Strategy:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        if (dv.visual_strategy.approach) {
          pdf.text(`Approach: ${dv.visual_strategy.approach}`, margin + 2, yPosition);
          yPosition += 4;
        }
        if (dv.visual_strategy.camera_personality) {
          pdf.text(`Camera: ${dv.visual_strategy.camera_personality}`, margin + 2, yPosition);
          yPosition += 4;
        }
        if (dv.visual_strategy.lighting_mood) {
          pdf.text(`Lighting: ${dv.visual_strategy.lighting_mood}`, margin + 2, yPosition);
          yPosition += 4;
        }
        yPosition += 2;
        checkPageBreak(20);
      }

      // Subtext
      if (dv.subtext) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Subtext:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        const subtextLines = pdf.splitTextToSize(dv.subtext, maxWidth - 5);
        yPosition += 4;
        pdf.text(subtextLines, margin + 2, yPosition);
        yPosition += subtextLines.length * 3.5 + 4;
        checkPageBreak(20);
      }

      // Conflict
      if (dv.conflict) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Conflict:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        if (dv.conflict.type) {
          pdf.setFont("helvetica", "bold");
          pdf.text(`Type: ${dv.conflict.type}`, margin + 2, yPosition);
          pdf.setFont("helvetica", "normal");
          yPosition += 4;
        }
        if (dv.conflict.description) {
          const conflictLines = pdf.splitTextToSize(dv.conflict.description, maxWidth - 5);
          pdf.text(conflictLines, margin + 2, yPosition);
          yPosition += conflictLines.length * 3.5;
        }
        if (dv.conflict.winner) {
          pdf.text(`Winner: ${dv.conflict.winner}`, margin + 2, yPosition);
          yPosition += 4;
        }
        yPosition += 2;
        checkPageBreak(20);
      }

      // Key Moments
      if (dv.key_moments && dv.key_moments.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Key Moments:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        dv.key_moments.forEach((moment, idx) => {
          checkPageBreak(15);
          if (moment.beat) {
            const beatLines = pdf.splitTextToSize(`${idx + 1}. ${moment.beat}`, maxWidth - 10);
            pdf.text(beatLines, margin + 2, yPosition);
            yPosition += beatLines.length * 3.5;
          }
          if (moment.why) {
            pdf.setTextColor(80, 80, 80);
            const whyLines = pdf.splitTextToSize(`   → ${moment.why}`, maxWidth - 15);
            pdf.text(whyLines, margin + 2, yPosition);
            yPosition += whyLines.length * 3.5;
            pdf.setTextColor(0, 0, 0);
          }
          yPosition += 2;
        });
        yPosition += 2;
        checkPageBreak(20);
      }

      // Character Motivations
      if (dv.character_motivations && dv.character_motivations.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Character Motivations:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        dv.character_motivations.forEach((char) => {
          checkPageBreak(15);
          if (char.character) {
            pdf.setFont("helvetica", "bold");
            pdf.text(char.character, margin + 2, yPosition);
            pdf.setFont("helvetica", "normal");
            yPosition += 4;
          }
          if (char.wants) {
            pdf.text(`  Wants: ${char.wants}`, margin + 2, yPosition);
            yPosition += 4;
          }
          if (char.obstacle) {
            pdf.text(`  Obstacle: ${char.obstacle}`, margin + 2, yPosition);
            yPosition += 4;
          }
          if (char.tactic) {
            pdf.text(`  Tactic: ${char.tactic}`, margin + 2, yPosition);
            yPosition += 4;
          }
          yPosition += 2;
        });
        checkPageBreak(20);
      }

      // Blocking
      if (dv.blocking) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Blocking:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        if (dv.blocking.geography) {
          const geoLines = pdf.splitTextToSize(`Geography: ${dv.blocking.geography}`, maxWidth - 5);
          pdf.text(geoLines, margin + 2, yPosition);
          yPosition += geoLines.length * 3.5;
        }
        if (dv.blocking.movement) {
          const moveLines = pdf.splitTextToSize(`Movement: ${dv.blocking.movement}`, maxWidth - 5);
          pdf.text(moveLines, margin + 2, yPosition);
          yPosition += moveLines.length * 3.5;
        }
        if (dv.blocking.eyelines) {
          const eyeLines = pdf.splitTextToSize(`Eyelines: ${dv.blocking.eyelines}`, maxWidth - 5);
          pdf.text(eyeLines, margin + 2, yPosition);
          yPosition += eyeLines.length * 3.5;
        }
        yPosition += 2;
        checkPageBreak(20);
      }

      // Performance Notes
      if (dv.performance_notes) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Performance Notes:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        const notes = Array.isArray(dv.performance_notes) ? dv.performance_notes : [dv.performance_notes];
        notes.forEach((note) => {
          checkPageBreak(10);
          const noteLines = pdf.splitTextToSize(`• ${note}`, maxWidth - 10);
          pdf.text(noteLines, margin + 2, yPosition);
          yPosition += noteLines.length * 3.5 + 2;
        });
        yPosition += 2;
      }

      yPosition += 4;
    }

    // ═══════════════════════════════════════════════════════════════
    // PRODUCING NOTES
    // ═══════════════════════════════════════════════════════════════
    const pl = analysis.producing_logistics;
    const hasProducingNotes = (pl?.red_flags?.length > 0) || 
                              (pl?.key_props?.length > 0) ||
                              (pl?.special_requirements?.length > 0) ||
                              pl?.locations ||
                              pl?.cast;
    
    if (hasProducingNotes) {
      checkPageBreak(30);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(229, 9, 20);
      pdf.text("PRODUCING NOTES", margin, yPosition);
      yPosition += 6;
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(8);

      // Location
      if (pl?.locations?.primary) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Location:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        pdf.text(pl.locations.primary, margin + 2, yPosition);
        yPosition += 6;
      }

      // Cast
      if (pl?.cast?.principal?.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Cast:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        pdf.text(`Principal: ${pl.cast.principal.join(", ")}`, margin + 2, yPosition);
        yPosition += 4;
        if (pl.cast.speaking?.length > 0) {
          pdf.text(`Speaking: ${pl.cast.speaking.join(", ")}`, margin + 2, yPosition);
          yPosition += 4;
        }
        if (pl.cast.silent?.length > 0) {
          pdf.text(`Silent: ${pl.cast.silent.join(", ")}`, margin + 2, yPosition);
          yPosition += 4;
        }
        yPosition += 2;
      }

      // Key Props
      if (pl?.key_props?.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Key Props:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        pdf.text(pl.key_props.join(", "), margin + 2, yPosition);
        yPosition += 6;
      }

      // Resource Impact
      if (pl?.resource_impact) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Resource Impact:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        pdf.text(pl.resource_impact, margin + 2, yPosition);
        yPosition += 6;
      }

      // Budget Flags
      if (pl?.red_flags?.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(200, 0, 0);
        pdf.text("Budget Flags:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
        yPosition += 4;
        pl.red_flags.forEach(flag => {
          const flagLines = pdf.splitTextToSize(`• ${flag}`, maxWidth - 10);
          pdf.text(flagLines, margin + 2, yPosition);
          yPosition += flagLines.length * 3.5 + 2;
        });
      }
      yPosition += 4;
    }

    // ═══════════════════════════════════════════════════════════════
    // SHOT LIST TABLE
    // ═══════════════════════════════════════════════════════════════
    if (analysis.shot_list && analysis.shot_list.length > 0) {
      checkPageBreak(40);
      
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(229, 9, 20);
      pdf.text(`SHOT LIST (${analysis.shot_list.length} shots)`, margin, yPosition);
      yPosition += 8;

      // Table header
      pdf.setFillColor(50, 50, 50);
      pdf.rect(margin, yPosition - 3, maxWidth, 7, 'F');
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(7);
      pdf.setTextColor(255, 255, 255);
      pdf.text("SHOT", margin + 2, yPosition + 1);
      pdf.text("TYPE", margin + 18, yPosition + 1);
      pdf.text("SUBJECT/DESCRIPTION", margin + 45, yPosition + 1);
      pdf.text("RATIONALE", margin + 120, yPosition + 1);
      yPosition += 7;

      // Shot rows
      analysis.shot_list.forEach((shot, shotIndex) => {
        checkPageBreak(12);

        // Alternating row colors
        if (shotIndex % 2 === 0) {
          pdf.setFillColor(245, 245, 245);
          pdf.rect(margin, yPosition - 2, maxWidth, 9, 'F');
        }

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(7);
        pdf.setTextColor(0, 0, 0);

        // Shot number
        pdf.setFont("helvetica", "bold");
        pdf.text(`${scene.scene_number}.${shotIndex + 1}`, margin + 2, yPosition + 3);

        // Shot type
        const shotType = shot.shot_type || 'WIDE';
        const movement = shot.movement && shot.movement !== 'STATIC' ? `/${shot.movement}` : '';
        pdf.setFont("helvetica", "normal");
        pdf.text(`${shotType}${movement}`.substring(0, 12), margin + 18, yPosition + 3);

        // Subject/Description
        const subjectText = (shot.subject || shot.visual || shot.visualDescription || '').substring(0, 50);
        pdf.text(subjectText, margin + 45, yPosition + 3);

        // Rationale
        pdf.setTextColor(80, 80, 80);
        const rationaleText = (shot.rationale || '').substring(0, 30);
        pdf.text(rationaleText, margin + 120, yPosition + 3);

        yPosition += 9;
      });

      yPosition += 6;
    }
  });

  // Footer on all pages
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} • ${projectTitle} • ShotLogic`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' }
    );
  }

  pdf.save(`${projectTitle}-full-analysis.pdf`);
};

// ═══════════════════════════════════════════════════════════════
// STORYBOARD PDF EXPORT
// ═══════════════════════════════════════════════════════════════
export const exportStoryboardPDF = async (scenes: Scene[], projectTitle: string, panelsPerPage: number = 6) => {
  const pdf = new jsPDF('landscape');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 10;
  let yPosition = 15;

  // Title
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(229, 9, 20);
  pdf.text(`STORYBOARD: ${projectTitle}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  // Grid layout based on panelsPerPage
  // 4 panels = 2x2, 6 panels = 3x2, 9 panels = 3x3
  const cols = panelsPerPage === 4 ? 2 : 3;
  const rows = panelsPerPage === 9 ? 3 : 2;
  
  const availableWidth = pageWidth - (margin * 2) - ((cols - 1) * 8);
  const availableHeight = pageHeight - 35 - ((rows - 1) * 20);
  const frameWidth = availableWidth / cols;
  const frameHeight = availableHeight / rows;
  const framePadding = 8;
  let frameIndex = 0;

  scenes.forEach((scene) => {
    const analysis = parseAnalysis(scene.analysis);
    if (!analysis?.shot_list) return;

    analysis.shot_list.forEach((shot, shotIdx) => {
      // Calculate position in grid
      const col = frameIndex % cols;
      const row = Math.floor(frameIndex / cols) % rows;
      
      // New page every panelsPerPage frames
      if (frameIndex > 0 && frameIndex % panelsPerPage === 0) {
        pdf.addPage();
        pdf.setFillColor(255, 255, 255);
        pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      }

      const xPos = margin + col * (frameWidth + framePadding);
      const yPos = 25 + row * (frameHeight + 20);

      // Frame border
      pdf.setDrawColor(100, 100, 100);
      pdf.setLineWidth(0.5);
      pdf.rect(xPos, yPos, frameWidth, frameHeight);

      // Frame placeholder (for image)
      pdf.setFillColor(240, 240, 240);
      pdf.rect(xPos + 1, yPos + 1, frameWidth - 2, frameHeight - 15, 'F');

      // Shot number badge
      pdf.setFillColor(229, 9, 20);
      pdf.rect(xPos + 2, yPos + 2, 18, 6, 'F');
      pdf.setFontSize(6);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(255, 255, 255);
      pdf.text(`${scene.scene_number}.${shotIdx + 1}`, xPos + 4, yPos + 6);

      // Shot type
      pdf.setFillColor(50, 50, 50);
      pdf.rect(xPos + 22, yPos + 2, 20, 6, 'F');
      pdf.setFontSize(5);
      pdf.text(shot.shot_type || 'WIDE', xPos + 24, yPos + 6);

      // Subject/Description at bottom of frame
      pdf.setFillColor(255, 255, 255);
      pdf.rect(xPos + 1, yPos + frameHeight - 14, frameWidth - 2, 13, 'F');
      
      pdf.setFontSize(6);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(0, 0, 0);
      const maxSubjectLength = panelsPerPage === 4 ? 70 : 45;
      const subject = (shot.subject || shot.visual || shot.visualDescription || '').substring(0, maxSubjectLength);
      pdf.text(subject, xPos + 3, yPos + frameHeight - 9);

      pdf.setFontSize(5);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(80, 80, 80);
      const maxRationaleLength = panelsPerPage === 4 ? 80 : 50;
      const rationale = (shot.rationale || '').substring(0, maxRationaleLength);
      pdf.text(rationale, xPos + 3, yPos + frameHeight - 4);

      frameIndex++;
    });
  });

  // Footer on all pages
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(7);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} • ${projectTitle} • ShotLogic Storyboard`,
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  }

  pdf.save(`${projectTitle}-storyboard.pdf`);
};

// ═══════════════════════════════════════════════════════════════
// CSV EXPORT
// ═══════════════════════════════════════════════════════════════
export const exportShotListCSV = (scenes: Scene[], projectTitle: string) => {
  const rows: string[][] = [
    ['Scene', 'Shot', 'Type', 'Movement', 'Subject', 'Coverage', 'Rationale', 'Duration', 'Image Prompt']
  ];

  scenes.forEach((scene) => {
    const analysis = parseAnalysis(scene.analysis);
    if (!analysis || !analysis.shot_list) return;

    analysis.shot_list.forEach((shot, idx) => {
      rows.push([
        `Scene ${scene.scene_number}`,
        `${scene.scene_number}.${idx + 1}`,
        shot.shot_type || 'WIDE',
        shot.movement || 'STATIC',
        shot.subject || shot.visual || shot.visualDescription || '',
        shot.coverage || '',
        shot.rationale || '',
        shot.duration || 'Standard',
        shot.image_prompt || shot.aiImagePrompt || ''
      ]);
    });
  });

  const csvContent = rows.map(row => 
    row.map(cell => `"${(cell || '').replace(/"/g, '""')}"`).join(',')
  ).join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${projectTitle}-shot-list.csv`;
  link.click();
};
