import jsPDF from "jspdf";

interface ShotListItem {
  shot_number?: number;
  shot_type: string;
  movement?: string;
  subject?: string;
  action?: string;
  visual: string;
  rationale: string;
  editorial_intent?: string;
  duration?: string;
  image_prompt?: string;
}

interface Scene {
  id: string;
  scene_number: number;
  header: string;
  content: string;
  analysis: string | null;
  status: string;
}

interface AnalysisData {
  story_analysis: {
    stakes: string;
    ownership: string;
    breaking_point: string;
    key_props: string;
    synopsis?: string;
    subtext?: string;
  };
  producing_logistics: {
    red_flags: string[];
    resource_impact: "Low" | "Medium" | "High";
    departments_affected: string[];
    key_props?: string[];
    wardrobe?: string[];
    special_requirements?: string[];
  };
  directing_vision: {
    visual_metaphor: string;
    editorial_intent: string;
    shot_motivation: string;
    visual_approach?: string;
    performance_notes?: string;
  };
  shot_list?: ShotListItem[];
}

const parseAnalysis = (analysisString: string | null): AnalysisData | null => {
  if (!analysisString) return null;
  try {
    return JSON.parse(analysisString);
  } catch {
    return null;
  }
};

export const exportShotListPDF = async (scenes: Scene[], projectTitle: string) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = 20;

  const checkPageBreak = (neededSpace: number) => {
    if (yPosition + neededSpace > pageHeight - 20) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 20;
      return true;
    }
    return false;
  };

  // White background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title Page Header
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(229, 9, 20); // Netflix red
  pdf.text("SCENE ANALYSIS & SHOT LIST", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(0, 0, 0);
  pdf.text(projectTitle, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;

  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${scenes.length} Scenes • Generated by ShotLogic`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  scenes.forEach((scene, sceneIndex) => {
    const analysis = parseAnalysis(scene.analysis);
    if (!analysis) return;

    // Start each scene on new page (except first)
    if (sceneIndex > 0) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 20;
    }

    // ═══════════════════════════════════════════════════════════════
    // SCENE HEADER
    // ═══════════════════════════════════════════════════════════════
    pdf.setFillColor(40, 40, 40);
    pdf.rect(margin, yPosition - 5, maxWidth, 12, 'F');
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.setTextColor(255, 255, 255);
    pdf.text(`SCENE ${scene.scene_number}`, margin + 3, yPosition + 3);
    yPosition += 12;

    // Scene slug line
    pdf.setFillColor(60, 60, 60);
    pdf.rect(margin, yPosition - 3, maxWidth, 8, 'F');
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(255, 255, 255);
    const headerText = scene.header.substring(0, 100) + (scene.header.length > 100 ? '...' : '');
    pdf.text(headerText, margin + 3, yPosition + 2);
    yPosition += 12;

    // ═══════════════════════════════════════════════════════════════
    // STORY ANALYSIS SECTION
    // ═══════════════════════════════════════════════════════════════
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(229, 9, 20);
    pdf.text("STORY ANALYSIS", margin, yPosition);
    yPosition += 6;

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(8);

    // Synopsis
    if (analysis.story_analysis?.synopsis) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Synopsis:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const synopsisLines = pdf.splitTextToSize(analysis.story_analysis.synopsis, maxWidth - 5);
      yPosition += 4;
      pdf.text(synopsisLines, margin + 2, yPosition);
      yPosition += synopsisLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Conflict
    if (analysis.story_analysis?.ownership) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Conflict:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      yPosition += 4;
      pdf.text(analysis.story_analysis.ownership, margin + 2, yPosition);
      yPosition += 6;
      checkPageBreak(20);
    }

    // Scene Turn
    if (analysis.story_analysis?.breaking_point) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Scene Turn:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const turnLines = pdf.splitTextToSize(analysis.story_analysis.breaking_point, maxWidth - 5);
      yPosition += 4;
      pdf.text(turnLines, margin + 2, yPosition);
      yPosition += turnLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Stakes
    if (analysis.story_analysis?.stakes) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Stakes:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const stakesLines = pdf.splitTextToSize(analysis.story_analysis.stakes, maxWidth - 5);
      yPosition += 4;
      pdf.text(stakesLines, margin + 2, yPosition);
      yPosition += stakesLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    // Tone
    if (analysis.directing_vision?.visual_metaphor) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Tone:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      const toneLines = pdf.splitTextToSize(analysis.directing_vision.visual_metaphor, maxWidth - 5);
      yPosition += 4;
      pdf.text(toneLines, margin + 2, yPosition);
      yPosition += toneLines.length * 3.5 + 4;
      checkPageBreak(20);
    }

    yPosition += 4;

    // ═══════════════════════════════════════════════════════════════
    // PRODUCING NOTES (if any red flags or key props)
    // ═══════════════════════════════════════════════════════════════
    const hasProducingNotes = (analysis.producing_logistics?.red_flags?.length > 0) || 
                              (analysis.producing_logistics?.key_props?.length > 0) ||
                              (analysis.producing_logistics?.special_requirements?.length > 0);
    
    if (hasProducingNotes) {
      checkPageBreak(30);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(229, 9, 20);
      pdf.text("PRODUCING NOTES", margin, yPosition);
      yPosition += 6;
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(8);

      if (analysis.producing_logistics?.key_props?.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.text("Key Props:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        yPosition += 4;
        pdf.text(analysis.producing_logistics.key_props.join(", "), margin + 2, yPosition);
        yPosition += 6;
      }

      if (analysis.producing_logistics?.red_flags?.length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(200, 0, 0);
        pdf.text("Budget Flags:", margin, yPosition);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
        yPosition += 4;
        analysis.producing_logistics.red_flags.forEach(flag => {
          const flagLines = pdf.splitTextToSize(`• ${flag}`, maxWidth - 10);
          pdf.text(flagLines, margin + 2, yPosition);
          yPosition += flagLines.length * 3.5 + 2;
        });
      }
      yPosition += 4;
    }

    // ═══════════════════════════════════════════════════════════════
    // SHOT LIST TABLE
    // ═══════════════════════════════════════════════════════════════
    if (analysis.shot_list && analysis.shot_list.length > 0) {
      checkPageBreak(40);
      
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(229, 9, 20);
      pdf.text(`SHOT LIST (${analysis.shot_list.length} shots)`, margin, yPosition);
      yPosition += 8;

      // Table header
      pdf.setFillColor(50, 50, 50);
      pdf.rect(margin, yPosition - 3, maxWidth, 7, 'F');
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(7);
      pdf.setTextColor(255, 255, 255);
      pdf.text("SHOT", margin + 2, yPosition + 1);
      pdf.text("TYPE", margin + 18, yPosition + 1);
      pdf.text("DESCRIPTION", margin + 45, yPosition + 1);
      pdf.text("RATIONALE", margin + 125, yPosition + 1);
      yPosition += 7;

      // Shot rows - NUMBER RESETS TO 1 FOR EACH SCENE
      analysis.shot_list.forEach((shot, shotIndex) => {
        checkPageBreak(12);

        // Alternating row colors
        if (shotIndex % 2 === 0) {
          pdf.setFillColor(245, 245, 245);
          pdf.rect(margin, yPosition - 2, maxWidth, 9, 'F');
        }

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(7);
        pdf.setTextColor(0, 0, 0);

        // Shot number (resets per scene)
        pdf.setFont("helvetica", "bold");
        pdf.text(`${scene.scene_number}.${shotIndex + 1}`, margin + 2, yPosition + 3);

        // Shot type
        const shotType = shot.shot_type || 'WIDE';
        const movement = shot.movement && shot.movement !== 'STATIC' ? `/${shot.movement}` : '';
        pdf.setFont("helvetica", "normal");
        pdf.text(`${shotType}${movement}`.substring(0, 12), margin + 18, yPosition + 3);

        // Visual description
        const visualText = (shot.visual || shot.subject || '').substring(0, 55);
        pdf.text(visualText, margin + 45, yPosition + 3);

        // Rationale
        pdf.setTextColor(80, 80, 80);
        const rationaleText = (shot.rationale || '').substring(0, 35);
        pdf.text(rationaleText, margin + 125, yPosition + 3);

        yPosition += 9;
      });

      yPosition += 6;
    }
  });

  // Footer on all pages
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} • ${projectTitle} • ShotLogic`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' }
    );
  }

  pdf.save(`${projectTitle}-analysis-shotlist.pdf`);
};

export const exportShotListCSV = (scenes: Scene[], projectTitle: string) => {
  const rows: string[][] = [
    ['Scene', 'Shot', 'Type', 'Movement', 'Description', 'Rationale', 'Duration', 'Image Prompt']
  ];

  scenes.forEach((scene) => {
    const analysis = parseAnalysis(scene.analysis);
    if (!analysis || !analysis.shot_list) return;

    analysis.shot_list.forEach((shot, idx) => {
      rows.push([
        `Scene ${scene.scene_number}`,
        `${scene.scene_number}.${idx + 1}`,
        shot.shot_type || 'WIDE',
        shot.movement || 'STATIC',
        shot.visual || '',
        shot.rationale || '',
        shot.duration || 'MEDIUM',
        shot.image_prompt || ''
      ]);
    });
  });

  const csvContent = rows.map(row => 
    row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')
  ).join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${projectTitle}-shot-list.csv`;
  link.click();
};
